### ISSUE TITLE
assert в релизе как то не оч =) или это у  тебя тесты?

### ISSUE THREAD

**Issue by gerasimenkoab** [gerasimenkoab/simple_psf_extractor#2]
https://github.com/gerasimenkoab/simple_psf_extractor/blob/4c79988be5b1acdea1b6835918f32631666d36a3/src/extractor/auto_segmenter.py#L54

это прям первое что в глаза бросилось
assert в релизе как то не оч =) или это у  тебя тесты?

**Comment by IMZolin** [comment]
Скорее да, assert в данном случае для отладки, чтобы быстрее обнаружить ошибку. Если assert истинно, то ничего не происходит, а иначе человек увидит ошибку.

**Comment by gerasimenkoab** [comment]
Ну это понятно, я про то что  это нужно убирать если мержить в мейн. Для ошибок есть try и error в лог

**Comment by gerasimenkoab** [comment]
Там у тебя много ассертов прямо в трай блоках.

**Comment by IMZolin** [comment]
Понял, хорошо!

**Comment by IMZolin** [comment]
Обновил, запушил
